# Generated by Django 2.1.4 on 2019-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20190202_1650')]

    initial = True

    dependencies = [
        ('questionnaires', '0006_auto_20190122_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireCategoryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete='CASCADE', to='main.QuestionnaireCategory')),
                ('questionnaire', models.OneToOneField(on_delete='CASCADE', to='questionnaires.Questionnaire')),
            ],
        ),
    ]
