# Generated by Django 2.1.4 on 2019-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('questionnaires', '0001_initial'), ('questionnaires', '0002_auto_20190112_2111'), ('questionnaires', '0003_questionnaire_length'), ('questionnaires', '0004_auto_20190122_2016'), ('questionnaires', '0005_auto_20190122_2032'), ('questionnaires', '0006_auto_20190122_2035')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemResponseOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=750)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.IntegerField()),
                ('root', models.CharField(max_length=750)),
                ('questionnaire', models.ForeignKey(default=1, on_delete='CASCADE', to='questionnaires.Questionnaire')),
                ('score_reversed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='itemresponseoptions',
            name='item',
            field=models.ManyToManyField(to='questionnaires.QuestionnaireItem'),
        ),
        migrations.CreateModel(
            name='QuestionnaireScoringRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=750)),
                ('questionnaire', models.ForeignKey(on_delete='CASCADE', to='questionnaires.Questionnaire')),
                ('items', models.ManyToManyField(to='questionnaires.QuestionnaireItem')),
            ],
        ),
    ]
