# Generated by Django 2.1.4 on 2019-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_squashed_0006_auto_20190122_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireitem',
            name='score_reversed',
            field=models.BooleanField(),
        ),
    ]
