# Generated by Django 2.1.4 on 2019-01-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20190112_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
