# Generated by Django 2.1.4 on 2019-01-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questionnaire_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireScoringRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=750)),
                ('questionnaire', models.ForeignKey(on_delete='CASCADE', to='questionnaires.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='score_reversed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='scoring_rules',
            field=models.ManyToManyField(to='questionnaires.QuestionnaireScoringRule'),
        ),
    ]
