# Generated by Django 2.1.4 on 2019-01-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20190122_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairescoringrule',
            name='items',
            field=models.ManyToManyField(to='questionnaires.QuestionnaireItem'),
        ),
    ]
