# Generated by Django 2.1.4 on 2019-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete='CASCADE', to='questionnaires.QuestionnaireItem')),
                ('response', models.ManyToManyField(to='questionnaires.ItemResponseOptions')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('questionnaire', models.ManyToManyField(to='questionnaires.Questionnaire')),
                ('responses', models.ManyToManyField(to='measurements.MeasurementResponse')),
            ],
        ),
        migrations.AddField(
            model_name='measurementresponse',
            name='session',
            field=models.ForeignKey(on_delete='CASCADE', to='measurements.MeasurementSession'),
        ),
    ]
