# Generated by Django 2.1.4 on 2019-01-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='measurementresponse',
            name='response',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='questionnaires.ItemResponseOptions'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='measurementsession',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='questionnaire',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='questionnaires.Questionnaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='responses',
            field=models.ManyToManyField(blank=True, to='measurements.MeasurementResponse'),
        ),
    ]
