# Generated by Django 2.1.4 on 2019-03-16 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_squashed_0004_measurementsession_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsession',
            name='questionnaire',
            field=models.ForeignKey(on_delete='CASCADE', to='questionnaires.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
