# Generated by Django 2.1.4 on 2019-01-12 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurements', '0002_auto_20190112_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementsession',
            name='responses',
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
