# Generated by Django 2.1.4 on 2019-01-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20190112_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
